const environment = {
BACKEND_BASE_URL: import.meta.env.VITE_BACKEND_BASE_URL || "",
NEW_ADMIN_REGISTRATION_URL: import.meta.env.VITE_NEW_ADMIN_REGISTRATION_URL || "",
NEW_ADMIN_EMAIL_VERIFICATION_URL: import.meta.env.VITE_NEW_ADMIN_EMAIL_VERIFICATION_URL || "",

EXISTING_ADMIN_LOGIN_URL: import.meta.env.VITE_EXISTING_ADMIN_LOGIN_URL || "",

FETCH_LOGGED_IN_ADMIN_URL: import.meta.env.VITE_FETCH_LOGGED_IN_ADMIN_URL || "",
EXISTING_ADMIN_LOGOUT_URL: import.meta.env.VITE_EXISTING_ADMIN_LOGOUT_URL || "",
FETCH_PLAYERS_DETAILS_URL: import.meta.env.VITE_FETCH_PLAYERS_DETAILS_URL || "",
RESPONSE_PLAYERS_URL: import.meta.env.VITE_RESPONSE_PLAYERS_URL || "",
EXPORT_DATA_IN_EXCEL_URL: import.meta.env.VITE_EXPORT_DATA_IN_EXCEL_URL || ""
}

const envConfig = Object.freeze(environment)
export default envConfig